name: Deploy docker-react
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Tag Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.actor }}/sample-react-docker-app:${{ github.sha }}

      - name: Generate ZIP
        run: zip -r deploy-${{ github.sha }}.zip . -x '*.git*'

      - name: Deploy ZIP to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy-${{ github.sha }}.zip
          use_existing_version_if_available: false
          wait_for_deployment: true

      - name: Deployed!
        run: echo App deployed to ELB
